### ISSUE TITLE
Calling MATLAB functions from torch function

### ISSUE THREAD

**Issue by ArghyaPal** [coupriec/VideoPredictionICLR2016#3]
@MichaelMathieu: 
Though not a code issue - but my query is like this: 
I have an existing MATLAB (say, something.m file) and I need that MATLAB file to be called from the torch file:
`th train_iclr_model.lua`.

To be more specific: I need a function within `train_iclr_model.lua` - that will call `something.m` and will use `something.m` results (like: mat file) as a part of Video Prediction.

For example:  `th train_iclr_model.lua`   ---> within `train_iclr_model.lua` I need a function `CALL_MATLAB_M_FILE()
---------
---------
-------
end`

May you please help me to figure out that..

Regards

**Comment by MichaelMathieu** [comment]
Hi @ArghyaPal,

I don't have experience with that. Lua is able to load and run precompiled functions, so that should be possible, but I don't know how easy.

There is a torch package 'mattorch' that is able to read and write matlab tensor files. Maybe the easiest way would be to write the data as a Matlab file, call a matlab script on this file (using os.system), and then read the result back from Lua ? Of course that will be slower than directly calling the function, but if this call is not time critical, this would probably be the simplest solution, in my opinion.

Best,
Michael

**Comment by ArghyaPal** [comment]
Thank You @MichaelMathieu for your suggestion :-) 
I will try it, and, will get back to you if I succeed.
