### ISSUE TITLE
Input of the Generator G

### ISSUE THREAD

**Issue by ArghyaPal** [coupriec/VideoPredictionICLR2016#6]
Hi @MichaelMathieu , I have a small doubt: Is your generator G an **autoencoder** (X->z->X') or its a z-->X **likelihood network**. I mean generator of Adversarial Network.
Here z: sample from the distribution, and, X: generated future frame.

**Comment by MichaelMathieu** [comment]
Hi,

Thank you for your interest.
It is a predictor. I admit the naming in the paper can be confusing.
The model G takes input frames (the past), and generates one output frame (the predicted future). In this implementation, no noise z is added (so we ask the network to produce one possible future, not the whole distribution of possible futures).

I  wouldn't call it an autoencoder, since it is not trained for reconstruction (i.e. the target is different from the input).

Does that answer your question?

**Comment by ArghyaPal** [comment]
Thank you @MichaelMathieu  for this clear answer. Yeah, it's a very good and easy to follow paper. Only that part was not clear to me - but now it's clear. 

Thank You Again,
Regards.
